<?php

/**
 * @file
 * This is a simple module implementing a Webform hook to offer vocabulary terms
 * to be used as options in form components.
 */

/**
 * Implements hook_webform_select_options_info().
 */
function webform_term_opts_webform_select_options_info() {
  $items = array();

  $vocabularies = taxonomy_get_vocabularies();

  foreach ($vocabularies as $vocabulary) {
    /**
     * @todo Add a setting that enables each vocabulary to be shown here.
     */
    $items[$vocabulary->machine_name] = array(
      'title' => t('Vocabulary terms: ') . $vocabulary->name,
      'options callback' => 'webform_term_options_vocabulary_terms',
      'options arguments' => $vocabulary->machine_name,
    );
  }

  return $items;
}

/**
 * Option list containing all terms of specified vocabulary.
 */
function webform_term_options_vocabulary_terms($component, $flat, $vocabulary_machine_name) {
  $terms = array();
  $tree = taxonomy_get_tree($vocabulary_machine_name);
  $use_i18n = module_exists('i18n_taxonomy');

  foreach ($tree as $term) {
    $prefix = str_repeat('· ', $term->depth);
    $terms['tid_' . $term->tid] = ($use_i18n) ? $prefix . i18n_taxonomy_term_name($term) : $prefix . $term->name;
  }

  return $terms;
}
